version: '3.8'

services:
  app:
    build:
      context: ..  # Asegúrate de que este directorio contenga tu Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped  # Reinicia el contenedor a menos que se detenga manualmente
