apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: crashlp/nestjs-kubernetes-test:latest
        ports:
        - containerPort: 3000  

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
spec:
  type: NodePort  # Cambia a LoadBalancer si lo deseas en un entorno real
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001  # Puedes especificar un puerto dentro del rango permitido
  selector:
    app: nestjs-app
