name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: crashlp/nestjs-kubernetes-test:latest
          push: true

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f deployments/docker-compose.yml down
          docker-compose -f deployments/docker-compose.yml up -d
